config/routes.rb
Rails.application.routes.draw do
  	resources :categories ,only: [:index, :show]
	resources :posts
	root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	validates :name , presence: true 
	has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title , presence: true
	validates :category_id , presence: true
	belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  	@categories = Category.all
  end

  def show
  	@category = Category.find(params[:id])
  	@posts = @category.posts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
		@category = Category.all
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to posts_url
		else
			render :new
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
		@category = Category.all
	end

	def update
		@post = Post.find(params[:id])
		begin			
	  		@post.update!(post_params)
	  		redirect_to post_path(@post)
	  	rescue
	  		render :edit
	  	end 		
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
  		redirect_to posts_path
	end

	private
	def post_params
		params.require(:post).permit(:title , :body , :category_id)
	end	
end

app/views/categories/index.html.erb
<h1>Categories</h1>
<% @categories.each do |category| %>
	<h2><%= link_to category.name , category %></h2>
	<hr>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<% @posts.each do |post| %>
	<h2><%= link_to post.title , post %></h2>
	<p><%= post.body %><p>
	<hr>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>

  <%= f.label 'Title' %>
  <%= f.text_field :title %>
  <br /> <br />

  <%= f.label 'Body' %>
  <%= f.text_area :body %>
  <br /> <br />

  <%= f.select :category_id, Category.all.collect { |x| [x.name, x.id] }, {:include_blank => "Choose One" } %>
  

  <%= submit_tag "update" %>

<% end %>

app/views/posts/index.html.erb
<h1>Blog Posts</h1>

<%= link_to "Create new post" , new_post_url %>  |   <%= link_to "View Categories" , categories_url %>

<% @posts.each do |post| %>
	<h2><%= link_to post.title , post %></h2>
	<p><%= post.body %><p>
	<hr>
<% end %>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>

  <%= f.label 'Title' %>
  <%= f.text_field :title %>
  <br /> <br />

  <%= f.label 'Body' %>
  <%= f.text_area :body %>
  <br /> <br />

    <%= f.select :category_id, Category.all.collect { |x| [x.name, x.id] }, {:include_blank => "Choose One" } %>


  <%= submit_tag "create" %>

<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %><p>


<%= link_to "Edit" , edit_post_url %>  |  <%= link_to "Delete" , post_path , method: :delete,    data: { confirm: 'Are you sure?' } %> 